package com.jasper.microquizz;

import android.graphics.drawable.GradientDrawable;
import android.widget.ImageView;
import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.app.ProgressDialog;
import android.widget.Toast;

import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseUser;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.DatabaseReference;

public class FeedbackActivity extends AppCompatActivity {
    private EditText tekstvak;
    private Button btn_verstuur;
    private ImageView iv_back;
    private ProgressDialog progressDialog;
    private FirebaseAuth firebaseAuth;
    private DatabaseReference mDatabase;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_feedback);

        progressDialog = new ProgressDialog(this);
        firebaseAuth = FirebaseAuth.getInstance();
        FirebaseUser user = firebaseAuth.getCurrentUser();
        mDatabase = FirebaseDatabase.getInstance().getReference();
        initControl();
        setBackGroundColors();

        btn_verstuur.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                FirebaseUser firebaseUser = firebaseAuth.getCurrentUser();
                final FirebaseDatabase database = FirebaseDatabase.getInstance();
                DatabaseReference ref = database.getReference("server/saving-data/fireblog");
                DatabaseReference postsRef = ref.child("posts");
                DatabaseReference newPostRef = postsRef.push();

                // de data wordt uit de vakjes gehaald en in een string gezet
                String tekst = tekstvak.getText().toString().trim();
                String gebruiker = firebaseUser.getEmail().toString();
                if (tekst.isEmpty()) {
                    Toast.makeText(FeedbackActivity.this, "Voer alstublieft alles in", Toast.LENGTH_SHORT).show();
                } else {
                    progressDialog.setMessage("laden");
                    progressDialog.show();
                    // Generate a reference to a new location and add some data using push()
                    DatabaseReference pushedPostRef = postsRef.push();

                    // Get the unique ID generated by a push()
                    String feedbackId = pushedPostRef.getKey();

                    // de data wordt in de database gezet
                    mDatabase.child("feedback").child(feedbackId).child("tekst").setValue(tekst);
                    mDatabase.child("feedback").child(feedbackId).child("gebruiker").setValue(gebruiker);

                    startActivity(new Intent(FeedbackActivity.this, HomeActivity.class));
                    progressDialog.dismiss();
                    Toast.makeText(FeedbackActivity.this, "Bedankt voor de feedback", Toast.LENGTH_LONG).show();
                }
            }
        });


        iv_back.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                startActivity(new Intent(FeedbackActivity.this, HomeActivity.class));
            }
        });
     }

    public void initControl() {
        btn_verstuur = findViewById(R.id.btn_verstuur);
        iv_back = findViewById(R.id.ivBack);
        tekstvak = findViewById(R.id.ET_tekstvak);
    }

    public void setBackGroundColors() {
        GradientDrawable btn_verstuur_bg = (GradientDrawable) btn_verstuur.getBackground();
        btn_verstuur_bg.setColor(getResources().getColor(R.color.colorBlue));
    }
}
